### PR TITLE
fix: update rn types and type fix plus upstream lib compilation change

### PR DESCRIPTION
**Pull request by filipef101**
There was no lib update on commit https://github.com/lukebrandonfarrell/react-native-navigation-drawer-extension/commit/2118b4e32b2fdc3ab8bf42a168d0fc4ed3dc86a0

This also fixes a typescript error I found when compiling it and while at it update types to latest RN

### CODE REVIEW

**Comment by filipef101** [comment]
@dorukcan Just a friendly reminder to use semantic commits otherwise CI won't trigger releases

**Comment by filipef101** [comment]
Not sure if I should commit the lib changes, or if that is done on CI? I'm assuming it's not part of CI

**Comment by lukebrandonfarrell** [comment]
Looks good to me @filipef101 :)

**Comment by lukebrandonfarrell** [comment]
@all-contributors add @filipef101 for code

**Comment by lukebrandonfarrell** [comment]
@all-contributors add @filipef101 for code

**Pull request merged**
